### ISSUE TITLE
Can I use it on Openbox with lxpanel?

### ISSUE THREAD

**Issue by root2185** [AyatanaIndicators/ayatana-indicator-application#18]
```
Debian 11
ayatana-indicator-application 0.8.0-1
```
I can see that LXDE is supported.
The file `/etc/xdg/autostart/ayatana-indicator-application.desktop` doesn't have it:
`OnlyShowIn=Unity;MATE;XFCE;Budgie;`

If I launch it I don't see anything new.

The `ayatana-indicator-datetime` package needs `mate-desktop` as a dependency.  So all Mate.
Do you need to have `mate-panel`? Is it DE independent?

**Comment by tari01** [comment]
> ```
> Debian 11
> ayatana-indicator-application 0.8.0-1
> ```
> 
> I can see that LXDE is supported. The file `/etc/xdg/autostart/ayatana-indicator-application.desktop` doesn't have it: `OnlyShowIn=Unity;MATE;XFCE;Budgie;`
> 
> If I launch it I don't see anything new.
> 
> The `ayatana-indicator-datetime` package needs `mate-desktop` as a dependency. So all Mate. Do you need to have `mate-panel`? Is it DE independent?

I guess you have figured this one out by now, but I'll answer just for the record. From what I can see [here](https://github.com/lxde/lxpanel/blob/master/plugins/indicator/indicator.c), the LXDE panel seems to support the old (and dead) Canonical indicators only. Once/If they switch to Ayatana, you will be able to use the new indicators. So nothing right now, I'm afraid...

I am closing this as answered. Feel free to reopen if I have given incorrect information.
