### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by SolarAquarion** [AyatanaIndicators/ayatana-indicator-application#2]
/bin/sh ../libtool   --mode=install /usr/bin/install -c   libayatana-application.la '/usr/lib/ayatana-indicators3/7/'
libtool:   error: error: cannot install 'libayatana-application.la' to a directory not ending in /usr/lib/ayatana-indicators3/7/

**Comment by tari01** [comment]
@SolarAquarion 

Is this still an issue? If so, could  you provide some info (which distro/desktop, your exact build command)

**Comment by SolarAquarion** [comment]
this issue doesn't occur if you build it in a chroot, but i use arch linux

**Comment by tari01** [comment]
@SolarAquarion: The build commands used in the AUR package work for me. Are you using different build options?
